apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mytestsecret
spec:
  backendType: secretsManager
  controllerId: external-secrets
  data:
    - key: externalsecrets/test1
      name: password
      property: password
    - key: externalsecrets/test1
      name: username
      property: username
    - key: externalsecrets/test1
      name: email
      property: email
  template:
    stringData:
      spring.datasource.url: 'username:<%= data.username %>,password:<%= data.password %>'