apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: subchart
    repoURL: https://github.com/pittar/gitops-catalog.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
